all:
  hosts: 

  children:
  
    5gcore:
      hosts:
        open5gs:
          ansible_host: 192.168.122.61
        upf:
          ansible_host: 192.168.122.10
  
    ue:
      hosts:  
        ueransim:
          ansible_host: 192.168.122.72
  
  vars:
    ansible_user: user5g