all:
  hosts: 

  children:
  
    5gcore:
      hosts:
        free5gc:
          ansible_host: 192.168.122.173
  
    ue:
      hosts:  
        ueransim:
          ansible_host: 192.168.122.72
  
  vars:
    ansible_user: user5g