- name: Setup Free5GC UPF
  hosts: upf

  environment:
    GOPATH: '/home/user5g/go'
    GOROOT: '/usr/local/go'
    PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/usr/local/go/bin'
    GO111MODULE: 'auto'

  tasks:

    - name: Print environment
      ansible.builtin.debug:
        msg: "{{ ansible_env }}"

    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Print message
      ansible.builtin.debug:
        msg: Hello world

    # Disable unattended-upgrades
    - name: Disable unattended-upgrades
      ansible.builtin.systemd:
        state: stopped
        name: unattended-upgrades
        enabled: false
      become: true

    - name: Install wget git curl
      ansible.builtin.apt:
        name:
          - wget
          - git
          - curl
        update_cache: true
        state: present
      become: true
    - name: Download Go
      ansible.builtin.script:
        cmd: ~/Documents/Bachelor/5gops/Free5GCUERANSIM/getGo.sh --creates installed-go.txt

    - name: Install Go
      ansible.builtin.script:
        cmd: ~/Documents/Bachelor/5gops/Free5GCUERANSIM/copyGo.sh
      become: true

    - name: Install prerequities for free5gc
      ansible.builtin.apt:
        name:
          - gcc
          - g++
          - cmake
          - autoconf
          - libtool
          - pkg-config
          - libmnl-dev
          - libyaml-dev
        state: present
      become: true

    - name: Setup Network configuration
      ansible.builtin.script:
        cmd: ~/Documents/Bachelor/5gops/Free5GCUERANSIM/netconf.sh
      become: true

    - name: Clone a repo with separate git directory
      ansible.builtin.git:
        repo: https://github.com/free5gc/free5gc.git
        dest: ~/free5gc
        clone: true
        version: 'v3.2.1'
        update: false

    - name: Build free5gc upf
      make:
        chdir: ~/free5gc
        target: upf

    # Install UPF
    - name: Get UPF via Git
      ansible.builtin.git:
        repo: https://github.com/free5gc/gtp5g.git
        dest: ~/gtp5g
        version: 'v0.6.8'
        update: false

    - name: Build UPF via make
      make:
        chdir: ~/gtp5g

    - name: Install UPF
      make:
        chdir: /home/user5g/gtp5g
        target: install
      become: true

    # Configure UPF
    - name: Expose PFCP IP Address
      ansible.builtin.replace:
        path: ~/free5gc/config/upfcfg.yaml
        regexp: '^pfcp:\n.*\n.*'
        replace: 'pfcp:\n  addr: 192.168.122.10\n  nodeID: 192.168.122.10'

    # Configure UPF
    - name: Expose GTPU IP Address
      ansible.builtin.replace:
        path: ~/free5gc/config/upfcfg.yaml
        regexp: '^.*ifList:\n.*'
        replace: '  ifList:\n    - addr: 192.168.122.10'

    # Run free5gc
    - name: Run the UPF
      ansible.builtin.script:
        cmd: ~/Documents/Bachelor/5gops/Free5GCUERANSIMUPF/runFree5GCUPF.sh
      become: true
